# Generated by Django 5.2.1 on 2025-06-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('value', models.IntegerField(default=0, verbose_name='Qiymat')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
            ],
        ),
    ]
