version: '3.8'

services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings # Loyiha nomingizga moslang

  frontend:
    build:
      context: ./src
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app/frontend
    depends_on:
      - backend